#!name=SnapEdit Pro
#!desc=Mở khóa tính năng Pro cho SnapEdit
# Bản Quyền Thuộc Về Quốc Chiến ❤️‍🩹
# Tham Gia Nhóm Telegram Để Được Hỗ Trợ: https://t.me/shadowrocketunlockproapps

[General]
skip-proxy = 127.0.0.1, ::1
bypass-system = true
tun-excluded-routes = 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12
private-ip-range = 127.0.0.1, 172.16.0.0/12, 192.168.0.0/16

[Script]
# Script mở khóa SnapEdit Pro
snapedit_pro_unlock = type=http-response, pattern=^https?:\\/\\/.*\\.snapedit\\.com\\/api\\/v\\d\\/user\\/status$, requires-body=true, max-size=0, script-path=https://raw.githubusercontent.com/quocchienn/lockcrack/refs/heads/module/SnapEdit.js, timeout=60

[MITM]
hostname = *.snapedit.com